// scripts/data.js

const leagueData = [
    {
        position: 1,
        team: "Real Madrid",
        points: 78,
        played: 30,
        wins: 24,
        draws: 6,
        losses: 0,
    },
    {
        position: 2,
        team: "FC Barcelona",
        points: 75,
        played: 30,
        wins: 23,
        draws: 6,
        losses: 1,
    },
    {
        position: 3,
        team: "Atlético Madrid",
        points: 65,
        played: 30,
        wins: 19,
        draws: 8,
        losses: 3,
    },
    {
        position: 4,
        team: "Real Sociedad",
        points: 58,
        played: 30,
        wins: 17,
        draws: 7,
        losses: 6,
    },
    {
        position: 5,
        team: "Real Betis",
        points: 55,
        played: 30,
        wins: 16,
        draws: 7,
        losses: 7,
    },
    {
        position: 6,
        team: "Villarreal",
        points: 52,
        played: 30,
        wins: 15,
        draws: 7,
        losses: 8,
    },
    {
        position: 7,
        team: "Athletic Bilbao",
        points: 49,
        played: 30,
        wins: 14,
        draws: 7,
        losses: 9,
    },
    {
        position: 8,
        team: "Valencia",
        points: 46,
        played: 30,
        wins: 13,
        draws: 7,
        losses: 10,
    },
    {
        position: 9,
        team: "Sevilla",
        points: 43,
        played: 30,
        wins: 12,
        draws: 7,
        losses: 11,
    },
    {
        position: 10,
        team: "Celta Vigo",
        points: 40,
        played: 30,
        wins: 11,
        draws: 7,
        losses: 12,
    },
    {
        position: 11,
        team: "Osasuna",
        points: 37,
        played: 30,
        wins: 10,
        draws: 7,
        losses: 13,
    },
    {
        position: 12,
        team: "Getafe",
        points: 34,
        played: 30,
        wins: 9,
        draws: 7,
        losses: 14,
    },
    {
        position: 13,
        team: "Mallorca",
        points: 31,
        played: 30,
        wins: 8,
        draws: 7,
        losses: 15,
    },
    {
        position: 14,
        team: "Cádiz",
        points: 28,
        played: 30,
        wins: 7,
        draws: 7,
        losses: 16,
    },
    {
        position: 15,
        team: "Almería",
        points: 25,
        played: 30,
        wins: 6,
        draws: 7,
        losses: 17,
    },
    {
        position: 16,
        team: "Valladolid",
        points: 22,
        played: 30,
        wins: 5,
        draws: 7,
        losses: 18,
    },
];

const recentResults = [
    {
        date: "1 de marzo",
        opponent: "Real Madrid",
        result: "2-1",
        type: "victory",
    },
    {
        date: "8 de marzo",
        opponent: "FC Barcelona",
        result: "1-1",
        type: "draw",
    },
    {
        date: "15 de marzo",
        opponent: "Atlético Madrid",
        result: "3-0",
        type: "victory",
    },
    {
        date: "22 de marzo",
        opponent: "Valencia",
        result: "0-2",
        type: "defeat",
    },
    {
        date: "29 de marzo",
        opponent: "Sevilla",
        result: "2-1",
        type: "victory",
    },
    {
        date: "5 de abril",
        opponent: "Real Betis",
        result: "4-0",
        type: "victory",
    },
    {
        date: "12 de abril",
        opponent: "Villarreal",
        result: "2-2",
        type: "draw",
    },
    {
        date: "19 de abril",
        opponent: "Athletic Bilbao",
        result: "1-3",
        type: "defeat",
    },
];

const playerData = [
    {
        id: 1,
        name: "Karim Benzema",
        team: "Real Madrid",
        position: "Delantero",
        goals: 25,
        assists: 12,
        yellowCards: 2,
        redCards: 0,
    },
    {
        id: 2,
        name: "Robert Lewandowski",
        team: "FC Barcelona",
        position: "Delantero",
        goals: 28,
        assists: 8,
        yellowCards: 5,
        redCards: 0,
    },
    {
        id: 3,
        name: "Antoine Griezmann",
        team: "Atlético Madrid",
        position: "Delantero",
        goals: 15,
        assists: 14,
        yellowCards: 7,
        redCards: 1,
    },
    {
        id: 4,
        name: "Vinícius Jr.",
        team: "Real Madrid",
        position: "Delantero",
        goals: 18,
        assists: 10,
        yellowCards: 9,
        redCards: 0,
    },
    {
        id: 5,
        name: "Iago Aspas",
        team: "Celta Vigo",
        position: "Delantero",
        goals: 16,
        assists: 6,
        yellowCards: 6,
        redCards: 0,
    },
    {
        id: 6,
        name: "Pedri",
        team: "FC Barcelona",
        position: "Mediocampo",
        goals: 8,
        assists: 10,
        yellowCards: 3,
        redCards: 0,
    },
    {
        id: 7,
        name: "Luka Modrić",
        team: "Real Madrid",
        position: "Mediocampo",
        goals: 6,
        assists: 9,
        yellowCards: 4,
        redCards: 0,
    },
    {
        id: 8,
        name: "Mikel Merino",
        team: "Real Sociedad",
        position: "Mediocampo",
        goals: 5,
        assists: 11,
        yellowCards: 8,
        redCards: 0,
    },
    {
        id: 9,
        name: "Éder Militão",
        team: "Real Madrid",
        position: "Defensa",
        goals: 5,
        assists: 1,
        yellowCards: 10,
        redCards: 1,
    },
    {
        id: 10,
        name: "Thibaut Courtois",
        team: "Real Madrid",
        position: "Portero",
        goals: 0,
        assists: 0,
        yellowCards: 1,
        redCards: 0,
    },
];
